services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.10
    container_name: weaviate
    ports:
      - 8080:8080
      - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - weaviate-network

  python-app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - weaviate
    ports:
      - 8501:8501    
    networks:
      - weaviate-network

networks:
  weaviate-network: